"""add cascade delete to payment and account if user is deleted

Revision ID: 2de5da9163f3
Revises: 8e61e4bd95aa
Create Date: 2026-07-17 23:00:18.481470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de5da9163f3'
down_revision: Union[str, Sequence[str], None] = '8e61e4bd95aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('accounts_user_id_fkey'), 'accounts', type_='foreignkey')
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['login'], ondelete='CASCADE')
    op.drop_constraint(op.f('payments_user_id_fkey'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('payments_account_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['login'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_account_id_fkey'), 'payments', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key(op.f('payments_user_id_fkey'), 'payments', 'users', ['user_id'], ['login'])
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.create_foreign_key(op.f('accounts_user_id_fkey'), 'accounts', 'users', ['user_id'], ['login'])
    # ### end Alembic commands ###
