"""add full_name to admin

Revision ID: 8e61e4bd95aa
Revises: ba32a865002a
Create Date: 2026-07-17 19:15:10.231604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e61e4bd95aa'
down_revision: Union[str, Sequence[str], None] = 'ba32a865002a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('full_name', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'users', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('admins', 'full_name')
    # ### end Alembic commands ###
