"""return to int ID pk in users

Revision ID: c6488bc8b883
Revises: 2de5da9163f3
Create Date: 2026-07-17 23:10:50.419148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6488bc8b883'
down_revision: Union[str, Sequence[str], None] = '2de5da9163f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accounts_user_id_fkey', 'accounts', type_='foreignkey')
    op.drop_constraint('payments_user_id_fkey', 'payments', type_='foreignkey')

    # 2. Убираем старый PK (login) и добавляем новый автоинкрементный id
    op.drop_constraint('users_pkey', 'users', type_='primary')
    op.execute("CREATE SEQUENCE IF NOT EXISTS users_id_seq")
    op.add_column('users', sa.Column('id', sa.Integer, nullable=True))
    op.execute("UPDATE users SET id = nextval('users_id_seq')")
    op.alter_column('users', 'id', nullable=False)
    op.execute("ALTER SEQUENCE users_id_seq OWNED BY users.id")
    op.execute("ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval('users_id_seq')")
    op.create_primary_key('users_pkey', 'users', ['id'])

    # 3. accounts: конвертируем user_id из login(str) в id(int) через временный столбец
    op.add_column('accounts', sa.Column('user_id_new', sa.Integer))
    op.execute("""
        UPDATE accounts a
        SET user_id_new = u.id
        FROM users u
        WHERE a.user_id = u.login
    """)
    op.drop_column('accounts', 'user_id')
    op.alter_column('accounts', 'user_id_new', new_column_name='user_id')
    op.alter_column('accounts', 'user_id', nullable=False)

    # 4. payments: то же самое для user_id
    op.add_column('payments', sa.Column('user_id_new', sa.Integer))
    op.execute("""
        UPDATE payments p
        SET user_id_new = u.id
        FROM users u
        WHERE p.user_id = u.login
    """)
    op.drop_column('payments', 'user_id')
    op.alter_column('payments', 'user_id_new', new_column_name='user_id')
    op.alter_column('payments', 'user_id', nullable=False)

    # 5. payments.amount: INTEGER -> FLOAT (безопасно, без конфликта типов)
    op.alter_column('payments', 'amount', type_=sa.Float())

    # 6. Пересоздаём foreign key на новый users.id
    op.create_foreign_key('accounts_user_id_fkey', 'accounts', 'users', ['user_id'], ['id'])
    op.create_foreign_key('payments_user_id_fkey', 'payments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accounts_user_id_fkey', 'accounts', type_='foreignkey')
    op.drop_constraint('payments_user_id_fkey', 'payments', type_='foreignkey')

    op.alter_column('payments', 'amount', type_=sa.Integer())

    op.add_column('accounts', sa.Column('user_id_new', sa.String(50)))
    op.execute("""
        UPDATE accounts a
        SET user_id_new = u.login
        FROM users u
        WHERE a.user_id = u.id
    """)
    op.drop_column('accounts', 'user_id')
    op.alter_column('accounts', 'user_id_new', new_column_name='user_id')

    op.add_column('payments', sa.Column('user_id_new', sa.String(50)))
    op.execute("""
        UPDATE payments p
        SET user_id_new = u.login
        FROM users u
        WHERE p.user_id = u.id
    """)
    op.drop_column('payments', 'user_id')
    op.alter_column('payments', 'user_id_new', new_column_name='user_id')

    op.drop_constraint('users_login_key', 'users', type_='unique')
    op.drop_constraint('users_pkey', 'users', type_='primary')
    op.drop_column('users', 'id')
    op.create_primary_key('users_pkey', 'users', ['login'])

    op.create_foreign_key('accounts_user_id_fkey', 'accounts', 'users', ['user_id'], ['login'])
    op.create_foreign_key('payments_user_id_fkey', 'payments', 'users', ['user_id'], ['login'])
    # ### end Alembic commands ###